# Generated by Django 5.2 on 2025-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden cronológico', unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('dinastia', models.CharField(blank=True, default='', max_length=120)),
                ('reinado_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('reinado_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('imagen_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
