# Generated by Django 5.2 on 2025-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rey',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='rey',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reyes/'),
        ),
    ]
