# Generated by Django 5.2 on 2025-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_remove_rey_imagen_url_rey_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rey',
            name='apodo',
            field=models.CharField(blank=True, help_text='Apodo histórico (si lo tiene)', max_length=120, null=True),
        ),
    ]
