# Generated by Django 5.2 on 2025-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_rey_apodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rey',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen histórico breve para mostrar en el modal'),
        ),
    ]
