# Generated by Django 5.2 on 2026-05-26 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_rey_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rey',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Resumen histórico breve para mostrar en el modal'),
        ),
    ]
