# Generated by Django 4.0 on 2022-04-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatologiaTerciaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terciaria', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Patologia terciaria',
                'verbose_name_plural': 'Patologías terciarias',
                'ordering': ['terciaria'],
            },
        ),
        migrations.CreateModel(
            name='PatologiaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secundaria', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('terciaria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.patologiaterciaria')),
            ],
            options={
                'verbose_name': 'Patologia secundaria',
                'verbose_name_plural': 'Patologías secundarias',
                'ordering': ['secundaria'],
            },
        ),
        migrations.CreateModel(
            name='PatologiaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('secundaria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.patologiasecundaria')),
            ],
            options={
                'verbose_name': 'Patologia principal',
                'verbose_name_plural': 'Patologías principales',
                'ordering': ['principal'],
            },
        ),
    ]
