# Generated by Django 4.0 on 2022-04-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patologiasecundaria',
            name='terciaria',
        ),
        migrations.DeleteModel(
            name='PatologiaPrincipal',
        ),
        migrations.DeleteModel(
            name='PatologiaSecundaria',
        ),
        migrations.DeleteModel(
            name='PatologiaTerciaria',
        ),
    ]
