# Generated by Django 4.0 on 2022-10-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Fármaco')),
                ('efecto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Efecto')),
                ('gravedad', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Gravedad')),
            ],
            options={
                'verbose_name': 'Interaccion',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['farmaco'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Marca')),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Laboratorio')),
                ('visitador', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Visitador')),
                ('observaciones', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Patología')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='CIE-9')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
                'ordering': ['patologia'],
            },
        ),
        migrations.CreateModel(
            name='Presentaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=100, unique=True, verbose_name='Fármaco')),
                ('grupo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo')),
                ('subgrupo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subgrupo')),
                ('efecto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Efecto')),
                ('mecanismo_accion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Mecanismo de acción')),
                ('dosis_minima', models.FloatField(blank=True, null=True)),
                ('dosis_maxima', models.FloatField(blank=True, null=True)),
                ('intervalo_dosis', models.IntegerField(blank=True, null=True)),
                ('FG_quitar', models.IntegerField(blank=True, null=True)),
                ('FG_no_iniciar', models.IntegerField(blank=True, default='0')),
                ('unidades', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidades')),
                ('comentarios', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios')),
                ('ventajas', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ventajas')),
                ('inconvenientes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Inconvenientes')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Editado el')),
                ('interacciones', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.interacciones', verbose_name='Interacciones')),
                ('marca', models.ManyToManyField(blank=True, to='crud.Marca', verbose_name='Marca')),
                ('presentaciones', models.ManyToManyField(blank=True, max_length=100, to='crud.Presentaciones', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['farmaco'],
            },
        ),
        migrations.CreateModel(
            name='Riesgo_Vascular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Riesgo')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True, verbose_name='CIE-9')),
                ('opcion', models.IntegerField(choices=[(0, 'Seleccione patología a filtrar'), (1, 'TODOS LOS PACIENTES'), (2, 'Diabetes'), (3, 'Hipertensión'), (4, 'Tabaquismo'), (5, 'Insuficiencia renal crónica'), (6, 'Hipercolesterolemia'), (7, 'Hipertrigliceridemia'), (8, 'Hiperlipemia mixta'), (9, 'Ex-fumador')], default=1, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Editado el')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Riesgo_Vascular',
                'verbose_name_plural': 'Riesgo_Vasculars',
                'ordering': ['riesgo'],
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('nuhsa', models.CharField(db_column='NUHSA', max_length=12, primary_key=True, serialize=False, verbose_name='NUHSA')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento')),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('farmaco', models.ManyToManyField(blank=True, to='crud.Tratamiento')),
                ('patologia', models.ManyToManyField(blank=True, to='crud.Patologias')),
                ('riesgo_vascular', models.ManyToManyField(blank=True, to='crud.Riesgo_Vascular')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pacientes',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido1', 'apellido2'],
            },
        ),
    ]
