# Generated by Django 4.0 on 2022-10-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tratamiento',
            new_name='Farmacos',
        ),
        migrations.AlterModelOptions(
            name='farmacos',
            options={'ordering': ['farmaco'], 'verbose_name': 'Farmaco', 'verbose_name_plural': 'Farmacos'},
        ),
    ]
