# Generated by Django 4.0 on 2022-11-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_tratamiento_farmacos_alter_farmacos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacos',
            name='FG_15_29',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG 15-29'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='FG_30_44',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG 30-44'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='FG_45_59',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG 45-59'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='FG_60_89',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG 60-89'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='FG_mayor_90',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG mayor de 90'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='FG_menor_15',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FG menor de 15'),
        ),
    ]
