# Generated by Django 4.0 on 2022-11-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_farmacos_fg_15_29_farmacos_fg_30_44_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacos',
            name='dosis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
