# Generated by Django 4.0 on 2022-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_farmacos_dosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacos',
            name='dosis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis'),
        ),
    ]
