# Generated by Django 4.0 on 2022-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_farmacos_dosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacos',
            name='dosis',
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_15_29',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis 15-29'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_30_44',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis 30-44'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_45_59',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis 45-59'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_60_89',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis 60-89'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_FG_mayor_90',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis mayor 90'),
        ),
        migrations.AddField(
            model_name='farmacos',
            name='dosis_FG_menor_15',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis menor 15'),
        ),
    ]
