# Generated by Django 4.0 on 2022-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_farmacos_dosis_farmacos_dosis_15_29_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacos',
            name='farmaco',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Fármaco'),
        ),
    ]
