# Generated by Django 4.0 on 2023-01-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_farmacos_farmaco'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionClinicaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='situacion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patología Principal',
                'verbose_name_plural': 'Patologías Principales',
                'ordering': ['situacion'],
            },
        ),
        migrations.CreateModel(
            name='SituacionClinicaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='situacion')),
                ('activo', models.BooleanField(default=True)),
                ('situacion_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.situacionclinicaprincipal')),
            ],
            options={
                'verbose_name': 'Patología Secundaria',
                'verbose_name_plural': 'Patologías Secundarias',
                'ordering': ['situacion'],
            },
        ),
        migrations.CreateModel(
            name='SituacionClinicaTerciaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='situacion')),
                ('activo', models.BooleanField(default=True)),
                ('situacion_secundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.situacionclinicasecundaria')),
            ],
            options={
                'verbose_name': 'Patología Terciaria',
                'verbose_name_plural': 'Patologías Terciarias',
                'ordering': ['situacion'],
            },
        ),
    ]
