# Generated by Django 4.0 on 2023-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_situacionclinicaprincipal_situacionclinicasecundaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionclinicasecundaria',
            name='situacion_principal',
        ),
        migrations.AddField(
            model_name='situacionclinicasecundaria',
            name='situacion_principal',
            field=models.ManyToManyField(to='crud.SituacionClinicaPrincipal'),
        ),
        migrations.RemoveField(
            model_name='situacionclinicaterciaria',
            name='situacion_secundaria',
        ),
        migrations.AddField(
            model_name='situacionclinicaterciaria',
            name='situacion_secundaria',
            field=models.ManyToManyField(to='crud.SituacionClinicaSecundaria'),
        ),
    ]
