# Generated by Django 4.0 on 2023-01-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_situacionclinicasecundaria_situacion_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacionclinicasecundaria',
            name='situacion_principal',
        ),
        migrations.AddField(
            model_name='situacionclinicasecundaria',
            name='situacion_principal',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.situacionclinicaprincipal', verbose_name='situacion'),
        ),
        migrations.RemoveField(
            model_name='situacionclinicaterciaria',
            name='situacion_secundaria',
        ),
        migrations.AddField(
            model_name='situacionclinicaterciaria',
            name='situacion_secundaria',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.situacionclinicasecundaria', verbose_name='situacion'),
        ),
    ]
