# Generated by Django 4.1.7 on 2023-03-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_remove_situacionclinicasecundaria_situacion_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacos',
            name='interacciones',
        ),
        migrations.DeleteModel(
            name='Interacciones',
        ),
    ]
