# Generated by Django 4.1.7 on 2023-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_remove_farmacos_interacciones_delete_interacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacos',
            name='dosis_minima',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
