# Generated by Django 4.1.7 on 2023-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_farmacos_dosis_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacos',
            name='dosis_minima',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
