# Generated by Django 4.1.7 on 2023-03-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_farmacos_dosis_minima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacos',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='farmacos',
            name='presentaciones',
        ),
    ]
