# Generated by Django 4.1.7 on 2023-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_remove_farmacos_marca_remove_farmacos_presentaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacos',
            name='marca',
            field=models.ManyToManyField(blank=True, to='crud.marca', verbose_name='Marca'),
        ),
    ]
